version: '3.9'

services:
  smart-brain-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smartbrain
      - REDIS_URL=redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smartbrain-api

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartbrain
      - POSTGRES_HOST=postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes